version: "3.8"

services:
  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    depends_on:
      - mongodb
      - redis
    networks:
      - app_network
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_URI: "mongodb://mongodb:27017/mydatabase"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      PORT: "${PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app_network
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_SERVER_URL=http://backend:${PORT}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
